### ISSUE TITLE
Home page - tag presentation

### ISSUE THREAD

**Issue by JasminaPN** [keitaroinc/ckanext-kepa#26]
**Steps to reproduce the issue:**
1. Go to the Kepa metadata portal
2. Go to the Home page
3. On the main screen - under the search bar the tags from the datasets are presented

**Expected behavior**: the tags should be displayed in the same format as they are in the datasets

Example from other CKAN portal

![Image](https://github.com/keitaroinc/ckanext-kepa/assets/23238850/0b3b4d51-1d18-42f6-8a0b-355266a25e3f)

**Actual behavior**: the tags are displayed as text.

**Comment by blagojabozinovski** [comment]
The bug was becouse of some misconfiguration on local enviroment. After reinstaling and reconfiguring CKAN localy (this time CKAN 2.10.3 instead of CKAN 2.10.1) the popular tags are showing OK.


![Image](https://github.com/keitaroinc/ckanext-kepa/assets/62408051/b9c8b0a1-0409-46c3-8d5d-70d6cd50c31f)
